trident_support: trident_support.c
	gcc -O2 -g -Wall -Werror -Wextra -Wno-unused-parameter -I$(PFM_DIR)/include -DCONFIG_PFMLIB_DEBUG -DCONFIG_PFMLIB_OS_LINUX -D_GNU_SOURCE -o trident_support -static trident_support.c $(PFM_DIR)/lib/libpfm.a
